### ISSUE TITLE
Private Key Passphrase

### ISSUE THREAD

**Issue by Raznak** [sybrenstuvel/python-rsa#110]
Hello,

I can't find the way to encrypt the private key with a passphrase in the doc.
Is there a way to do that with your lib ?

Thanks

**Comment by sybrenstuvel** [comment]
Encrypting the private key is done using a symmetric encryption method (typically DES or 3DES) so that the same passphrase can be used for both encrypting and decrypting. My Python-RSA library only implements RSA encryption, so this is not possible with this library.
