### ISSUE TITLE
why rsa.prime.getprime gots prime numbe in so less times?

### ISSUE THREAD

**Issue by yunfan** [sybrenstuvel/python-rsa#111]
hi i was curious of rsa algorighm so i cloned this repo for learning
and i noticed that `rsa.prime.getprime` could got a acceptable prime number in a very less time from my view

for eg, i have invoked 1000 times `getprime(1024)` and found that the maxium loop time is 2600

are there any mathmetics princeples?

**Comment by sybrenstuvel** [comment]
It may appear counter-intuitive, but when you randomly pick a large enough number, there is a fair chance that it's prime already. Then there is the [Miller-Rabin primality test](https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test) which is quite fast at determining whether something is a prime number.
