### ISSUE TITLE
encrypt returns a bytes type result and cant convert it to str

### ISSUE THREAD

**Issue by leinue** [sybrenstuvel/python-rsa#113]
`_password == b'q\xa1\xc2\xc0\xfc%\x1f"\xaand\xcc@8\x1dR\x10\xe7\xeb\x1f\xe7\xdc9xX\xc1\x04\x80\x12A\\\xe8\xfe\xdc\xc1\xed\x19\xadU\xab\xbe\xfceL\x80\xc0\x8f+Q\x1b\xa9\x90\x0e\xd2\x8e\xeeb\xca\xa3Rxu\xf6\x91\xaeCr\x07\x01\xc7]l\xa9\xba\xab\x92\x19^4\xd1\xc8\xd2\x94\xdc\x04S[\xb4\xb1\x00\x98\xd0c4P\xa9\x11\xf8\'\xff\xf9dGq\xdd\xa5\xb4\\\x98\xdc\x91\x95S\xf27\xc1\xbb\x17tt\xceh\xcb\xa2/\xe8\xb3\xa9'`

``` python
   _password = rsa.encrypt(password.encode('utf8'), self.pubKey)
         """
_password == b'q\xa1\xc2\xc0\xfc%\x1f"\xaand\xcc@8\x1dR\x10\xe7\xeb\x1f\xe7\xdc9xX\xc1\x04\x80\x12A\\\xe8\xfe\xdc\xc1\xed\x19\xadU\xab\xbe\xfceL\x80\xc0\x8f+Q\x1b\xa9\x90\x0e\xd2\x8e\xeeb\xca\xa3Rxu\xf6\x91\xaeCr\x07\x01\xc7]l\xa9\xba\xab\x92\x19^4\xd1\xc8\xd2\x94\xdc\x04S[\xb4\xb1\x00\x98\xd0c4P\xa9\x11\xf8\'\xff\xf9dGq\xdd\xa5\xb4\\\x98\xdc\x91\x95S\xf27\xc1\xbb\x17tt\xceh\xcb\xa2/\xe8\xb3\xa9'
         """"
         
         str(_password, encoding='utf-8')
```

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 1: invalid start byte

**Comment by leinue** [comment]
I have fixed this:

``` javascript
base64.b64encode(_password).decode()
```

**Comment by sybrenstuvel** [comment]
The `rsa.encrypt()` function returns bytes, so there is no reason why this would be valid UTF-8. What are you trying to accomplish?

**Comment by leinue** [comment]
@sybrenstuvel I just wanted to jsonfiy the result

**Comment by sybrenstuvel** [comment]
In that case base64-encoding the data is indeed a good approach.
