### ISSUE TITLE
修改数据返回正确，前提是攻破服务器。

### ISSUE THREAD

**Issue by qvbgod96** [sybrenstuvel/python-rsa#118]
我给你这么说，签名和验签算法有问题。举个例
签名“再来一次”，验签“再来一次”，只需要验签的时间把n和e改成上一次的就会出现正确
用之前签的名来验证这一次会出现正确
解决办法是加上时间戳，但是把时间戳改成上一次又会正确。

**Comment by sybrenstuvel** [comment]
I can run that through Google Translate, but still I need more info. Please write in English or Dutch, those are the languages I can understand myself.

Also include a simple code example of the issue you're facing, so that I can run & see it for myself.

**Comment by yjqiang** [comment]
I'm from China and I'm sure this guy did not say any normal words. You can close it or even delete it.

**Comment by sybrenstuvel** [comment]
Thanks @yjqiang.
