### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by yjqiang** [sybrenstuvel/python-rsa#119]
“Version 3.4 is the last version in the 3.x range. Version 4.0 will drop the following modules”
But the lastest version (v3.4.2) was released 2 years ago.

**Comment by sybrenstuvel** [comment]
The remark is as true now as it was back then. You're right that I haven't had much time to spend on working on this project. It is alive, though, and I certainly accept (quality) pull requests.

**Comment by sybrenstuvel** [comment]
PS: feel free to keep talking here; I just marked it as "closed" to indicate the direct question has been answered.
