### ISSUE TITLE
Secure Request: SHA-3

### ISSUE THREAD

**Issue by yjqiang** [sybrenstuvel/python-rsa#128]
1. SHA2 is not secure enough now. [SHA-256 and SHA-512, and, to a lesser degree, SHA-224 and SHA-384 are prone to length extension attacks,[6] rendering it insecure for some applications. It is thus generally recommended to switch to SHA-3 for 512-bit hashes and to use SHA-512/224 and SHA-512/256 instead of SHA-224 and SHA-256. This also happens to be faster than SHA-224 and SHA-256 on x86-64 processor architecture, since SHA-512 works on 64-bit instead of 32-bit words.](https://en.wikipedia.org/wiki/SHA-2)

1. And python supported SHA3 already. [New in version 3.6: SHA3 (Keccak) and SHAKE constructors sha3_224(), sha3_256(), sha3_384(), sha3_512(), shake_128(), shake_256().](https://docs.python.org/3/library/hashlib.html) 

So, time to support SHA3 in sign function?

**Comment by sybrenstuvel** [comment]
Implemented in 3c5ee594a2e38b27f086d042d9d2b9d7d0d0269d

**Comment by sybrenstuvel** [comment]
Thanks for providing the context :)
