### ISSUE TITLE
Can't send data that is encrypted because it is of bytes type.

### ISSUE THREAD

**Issue by ameyanator** [sybrenstuvel/python-rsa#130]
rsa.encrypt() returns a bytes type object which I do not understand how to send across.

On using rsa.encrypt() I get a result such as b'...qwerty...'. When I send this message to the client side who uses input to read the message '...qwerty...' gets stored as a string and the client side decryption fails. Can you suggest some way to send the encrypted message to the client so that it can be decrypted properly over there?

I understand this is more of a python issue than one related to this project but any help is greatly appreciated.

**Comment by sybrenstuvel** [comment]
> rsa.encrypt() returns a bytes type object which I do not understand how to send across.

Across what? To what kind of client?

> I understand this is more of a python issue than one related to this project but any help is greatly appreciated.

So far it's mostly an issue with giving the info I actually need to help ;-)

**Comment by ameyanator** [comment]
I'm sorry I think I was not clear.

When I encrypt a using crypto = rsa.encrypt(message.encode('utf8',pubkey)). I get crypto as a bytes object. Now suppose I have already sent some client the private key corresponding to the public key I have just used. Now I am not able to send the client this encrypted message crypto because its a bytes object. (So when I copy the result of print(crypto) and send it to the client who does crypto = input('Enter encrypted text') crypto becomes a str object.)

How do I handle this?

**Comment by sybrenstuvel** [comment]
> When I encrypt [...] I get crypto as a bytes object.

Yes, that's how it should be. You shouldn't expect to get valid UTF-8 back after encryption.

> Now suppose I have already sent some client the private key corresponding to the public key I have just used.

This is rather strange. A private key is generally kept private, e.g. not sent to anyone. Typically someone (or something) creates a keypair, and sends the public key to the other side. What's the reason you're sending a private key anywhere?

> So when I copy the result of print(crypto) and send it to the client who does crypto = input('Enter encrypted text') crypto becomes a str object.

Ah, "sending" means "copy-pasting" in this case. This means that you'll have to convert the bytes into a copy-pastable form. There are many ways to do that, converting to [base64](https://docs.python.org/3/library/base64.html) being one of the most widely-used approaches.

**Comment by ameyanator** [comment]
I have understood. Thank You!
