### ISSUE TITLE
Problem when trying to decrypt a string sent from a socket

### ISSUE THREAD

**Issue by mokaytripsit** [sybrenstuvel/python-rsa#135]
Python 3.8.0
rsa 4.0

The client receives the public key the following way:
```
got_key = s.recv(4096)
server_public_key = rsa.PublicKey.load_pkcs1(keyfile=got_key)
```

Then the client encrypts with the key and sends it:
```
form_string_encrypted = rsa.encrypt(form_string.encode(), server_public_key)
s.sendall(form_string_encrypted)
```

The server reads it's private key:
```
f = open("server_private_key", 'r')
got_key = f.read()
f.close()
private_key = rsa.PrivateKey.load_pkcs1(keyfile=got_key.encode())
```

Then decrypts:
`decrypted_data = rsa.decrypt(received_data, private_key)`

I get an exception here ^

> rsa.pkcs1.DecryptionError: Decryption failed

And the weirdest thing I forgot to add is that the data itself gets decrypted.

I've had no problem when signing and verifying.

Something else I noticed is when I stop the threads I get this.

> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "...Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "...Python\Python38-32\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "...server.py", line 313, in accepted_connection
>     decrypted_data = rsa.decrypt(received_data, private_key)
>   File "...Python\Python38-32\lib\site-packages\rsa\pkcs1.py", line 233, in decrypt
>     encrypted = transform.bytes2int(crypto)
>   File "...Python\Python38-32\lib\site-packages\rsa\transform.py", line 43, in bytes2int
>     return int(binascii.hexlify(raw_bytes), 16)
> ValueError: invalid literal for int() with base 16: b''

**Comment by mokaytripsit** [comment]
Well, I'm an idiot. I was sending not encrypted data and was trying to decrypt it before decrypting this data. I hope that someone with a similar problem comes across this and it helps him. I really hope...

**Comment by televisionia** [comment]
Oh, well, congratulations... I'm having this same issue, but I'm receiving this error for different reasons

**Comment by sybrenstuvel** [comment]
@televisionia please file a report for your issue. That'll be more helpful than commenting on an old one.
