### ISSUE TITLE
Remove unneeded coding setting

### ISSUE THREAD

**Issue by and-semakin** [sybrenstuvel/python-rsa#138]
At the top of any file in this project we have following lines:
```python
# -*- coding: utf-8 -*-
#
```

I know that this is mandatory for Python 2 but as far as I know master branch is not compatible with Python 2 any more. For Python 3 this `coding` keyword is redundant, see [here](https://stackoverflow.com/a/14083123/10650942).

**Comment by and-semakin** [comment]
If there are no objections then I can create a PR and drop this lines.

**Comment by sybrenstuvel** [comment]
Please add a PR, changes like this are very welcome :)

**Comment by and-semakin** [comment]
Made a PR, will close this issue. Thank you!
