### ISSUE TITLE
Add Python 3.8 support

### ISSUE THREAD

**Issue by and-semakin** [sybrenstuvel/python-rsa#139]
It seems to me that there is no reason to this library not to work on Python 3.8.0 which was recently released.

**Comment by and-semakin** [comment]
I tried to add Python 3.8 to Travis matrix but had some issues with `importlib_metadata` dependency.

**Comment by sybrenstuvel** [comment]
I had the same issue. Turned out it was `pluggy` needing an update. Thanks for the poke, now Python-RSA 4.1 has been released with Python 3.8 support.
