### ISSUE TITLE
rsa.verify returns the the name of the used hash rather than a boolean

### ISSUE THREAD

**Issue by carlinmack** [sybrenstuvel/python-rsa#140]
Hi,

The [documentation](https://stuvel.eu/python-rsa-doc/usage.html#signing-and-verification) describes that it returns a boolean however the [implementation](https://github.com/sybrenstuvel/python-rsa/blob/master/rsa/pkcs1.py#L329) actually returns a Verification Error or the name of the hash. I'd fix this but I'm not sure if the documentation can be edited.

**Comment by carlinmack** [comment]
Additonally, and a seperate issue, the examples in the documentation no longer work out of the box as the message needs to be `.encode`'ed

**Comment by sybrenstuvel** [comment]
Thanks for pointing this out!

**Comment by myheroyuki** [comment]
This issue has been addressed:

1. The documentation was updated to reflect the correct return type/value of `rsa.verify`
2. The examples work out of the box since the message is now `encode()`ed
