### ISSUE TITLE
Add BLAKE2 support

### ISSUE THREAD

**Issue by yjqiang** [sybrenstuvel/python-rsa#143]
https://github.com/sybrenstuvel/python-rsa/pull/96
I checked black2s and black2b like 👆(sha3), and it works. But Python 3.6 has support for black2 in hashlib but older versions of Python do not. So what should we do? And sorry about that, I can't calculate asn1_code for black2, so I didn't pull request.

**Comment by yjqiang** [comment]
Update0: https://github.com/dchest/pyblake2  but it's not pure python.

**Comment by myheroyuki** [comment]
This library implements RSA according to PKCS#1, which does not include BLAKE2.
A case could be made to add support if BLAKE2 is frequently used with RSA in practice.
However, OpenSSL (one of the most popular cryptography libraries) does not support BLAKE2 with RSA, so adding this configuration would be unusual.

Please feel free to reopen this issue if you know of a compelling use case and we can reconsider adding BLAKE2 support.
