### ISSUE TITLE
Non-ASCII character '\\xc3' in file /usr/local/lib/python3.7/site-packages/rsa/__init__.py on line 1, but no encoding declared;

### ISSUE THREAD

**Issue by John-Oula** [sybrenstuvel/python-rsa#158]
I have chinese characters in my code but are already utf-8 encoded.It raises this error whenever I try to run my flask aoo on the server.

**Comment by sybrenstuvel** [comment]
This is strange, as this usually is an indication that you're running Python 2.7. The directory the code is in shows Python 3.7 though. How are you running the code?

**Comment by John-Oula** [comment]
Im running it on Apahe 16.04 with mod_wsgi

**Comment by John-Oula** [comment]
I added these lines __init__.py 
#!/usr/bin/env python
# -*- coding: utf-8 -*- 
and it kind of solved it.Now im getting this traceback error
 import rsa
[Wed Aug 12 00:05:17.627535 2020] [wsgi:error] [pid 12172] [remote 153.3.101.137:15124]   File "/usr/local/lib/python3.7/site-packages/rsa/__init__.py", line 26, in <module>
[Wed Aug 12 00:05:17.627554 2020] [wsgi:error] [pid 12172] [remote 153.3.101.137:15124]     from rsa.key import newkeys, PrivateKey, PublicKey
[Wed Aug 12 00:05:17.627577 2020] [wsgi:error] [pid 12172] [remote 153.3.101.137:15124]   File "/usr/local/lib/python3.7/site-packages/rsa/key.py", line 56
[Wed Aug 12 00:05:17.627580 2020] [wsgi:error] [pid 12172] [remote 153.3.101.137:15124]     def __init__(self, n: int, e: int) -> None:
[Wed Aug 12 00:05:17.627582 2020] [wsgi:error] [pid 12172] [remote 153.3.101.137:15124]                         ^

**Comment by sybrenstuvel** [comment]
If that is a syntax error, you're definitely not running Python 3.7. This is not the place for getting support with mod_wsgi though.

**Comment by sybrenstuvel** [comment]
In #160 you mentioned:

> Im am running the code on Apache 16.04 with mod-wsgi enabled..Python 3.7

You're mixing up your version numbers. Apache 2.4.46 was released on 2020-08-07 (source: https://httpd.apache.org/).

As I said before, the errors you're seeing is caused by running a too old, incompatible version of Python. Maybe you have added the Python 3.7 `site_packages` path to your `PYTHON_PATH` variable, so that it still loads code from there, but the Python is definitely older than 3.7.

If you're running Ubuntu 16.04 (just a guess based on the version number) your mod-wsgi is very likely using Python 2.7.

**Comment by John-Oula** [comment]
> In #160 you mentioned:
> 
> > Im am running the code on Apache 16.04 with mod-wsgi enabled..Python 3.7
> 
> You're mixing up your version numbers. Apache 2.4.46 was released on 2020-08-07 (source: https://httpd.apache.org/).
> 
> As I said before, the errors you're seeing is caused by running a too old, incompatible version of Python. Maybe you have added the Python 3.7 `site_packages` path to your `PYTHON_PATH` environment variable, so that it still loads code from there, but the Python is definitely older than 3.7.
> 
> If you're running Ubuntu 16.04 (just a guess based on the version number) your mod-wsgi is very likely using Python 2.7.

![Screenshot (262)](https://user-images.githubusercontent.com/44803250/89996599-92520580-dcbd-11ea-97d0-e65a4ec033d2.png)


I see.Could the shebang line be the cause of the problem?..on the wsgi file

**Comment by sybrenstuvel** [comment]
Run `/usr/bin/python --version` and see which version it is.

**Comment by John-Oula** [comment]
> Run `/usr/bin/python --version` and see which version it is.

It is Python 3.7.3

**Comment by sybrenstuvel** [comment]
Then you have to figure out which Python is used exactly by your mod_wsgi. But again, this is not the place to get help setting up a web server.
