### ISSUE TITLE
Syntax error in rsa.key def __init__(self, n: int, e: int) -> None:

### ISSUE THREAD

**Issue by John-Oula** [sybrenstuvel/python-rsa#160]
Im am running the code on Apache 16.04 with mod-wsgi enabled..Python 3.7

[Wed Aug 12 15:48:40.297614 2020] [wsgi:error] [pid 31225] [remote 153.3.101.137:33340]     import rsa
[Wed Aug 12 15:48:40.297618 2020] [wsgi:error] [pid 31225] [remote 153.3.101.137:33340]   File "/usr/local/lib/python3.7/site-packages/rsa/__init__.py", line 26, in <module>
[Wed Aug 12 15:48:40.297638 2020] [wsgi:error] [pid 31225] [remote 153.3.101.137:33340]     from rsa.key import newkeys, PrivateKey, PublicKey
[Wed Aug 12 15:48:40.297666 2020] [wsgi:error] [pid 31225] [remote 153.3.101.137:33340]   File "/usr/local/lib/python3.7/site-packages/rsa/key.py", line 56
[Wed Aug 12 15:48:40.297670 2020] [wsgi:error] [pid 31225] [remote 153.3.101.137:33340]     def __init__(self, n: int, e: int) -> None:
[Wed Aug 12 15:48:40.297672 2020] [wsgi:error] [pid 31225] [remote 153.3.101.137:33340]                         ^
[Wed Aug 12 15:48:40.297674 2020] [wsgi:error] [pid 31225] [remote 153.3.101.137:33340] SyntaxError: invalid syntax

**Comment by sybrenstuvel** [comment]
Please do not open multiple tickets for the same problem.
