### ISSUE TITLE
Security Policy?

### ISSUE THREAD

**Issue by tomato42** [sybrenstuvel/python-rsa#161]
What's the security policy for the package?

Which versions are supported?
What's the threat model?
How security issues should be reported?

**Comment by sybrenstuvel** [comment]
> What's the security policy for the package?
There is none.

> Which versions are supported?
That depends on what you mean with "supported". Bugs are fixed when they're reported.

>  What's the threat model?
There is none.

>  How security issues should be reported?
If they're sensitive, please send me an email at sybren@stuvel.eu, otherwise just report them here.

**Comment by tomato42** [comment]
> >    Which versions are supported?
>
> That depends on what you mean with "supported". Bugs are fixed when they're reported.

well, some libraries support just official releases, not the master branch, sometimes there are multiple branches supported at the same time, like 3.x and 4.x, and so on. Given that current releases don't support python 2.7, I'm guessing some people may want to know that they're unsupported.

> If they're sensitive, please send me an email at sybren@stuvel.eu, otherwise just report them here.

ok, in case it turns out to be sensitive, I have sent you an email

**Comment by tomato42** [comment]
@sybrenstuvel did you get the email? I didn't receive a reply...

**Comment by sybrenstuvel** [comment]
Nope, I didn't see any email.

**Comment by tomato42** [comment]
ok, I've sent it from a different address, please check now
