### ISSUE TITLE
The decryption code is PKCS#1 v1.5 non-compliant - no padding length check

### ISSUE THREAD

**Issue by tomato42** [sybrenstuvel/python-rsa#164]
the current code:
https://github.com/sybrenstuvel/python-rsa/blob/6f59ff07a317409fe68696935daf8549b1555c74/rsa/pkcs1.py#L246-L267

doesn't check that the length of the padding is at least 8 bytes.

See https://tools.ietf.org/html/rfc8017#section-7.2.2 step 3

**Comment by sybrenstuvel** [comment]
Thanks for the report. This is fortunately easy enough to fix after https://github.com/sybrenstuvel/python-rsa/issues/165#issuecomment-725436235 is implemented. Changing the line

```python
sep_idx_bad = sep_idx < 0
```
to
```python
sep_idx_bad = sep_idx < 8
```
should do the trick.
