### ISSUE TITLE
How to store the public and private key into the pem file 

### ISSUE THREAD

**Issue by VinayIsHere** [sybrenstuvel/python-rsa#171]
Hy thanks for this library, I am able to generate the public and private key in the code but I want to store this public and private jey into some file so that i can send it to someone and then want to read them from a file.
I have ready some of your examples but not able to understand.
Suppose I want to store the keys in ```key.pem``` tell me how can i achieve that

**Comment by sybrenstuvel** [comment]
The library doesn't deal with files. It can load keys from bytes, and save keys to bytes. It's up to your application to do something with the bytes, like save to a file, send over a network connection, etc.

Something like this would do it:

```python
import rsa

pubkey, privkey = rsa.newkeys(512)

with open('bothkeys.pem', 'wb') as pemfile:
    pemfile.write(pubkey.save_pkcs1())
    pemfile.write(privkey.save_pkcs1())
```
