### ISSUE TITLE
4.7.1 sdist does not set python_requires

### ISSUE THREAD

**Issue by saifelse** [sybrenstuvel/python-rsa#175]
See: https://pypi.org/pypi/rsa/4.7.1/json

It appears the 4.7.1 sdist had a regression where it incorrectly surfaces `"requires_python": null`, unlike the previous 4.7 sdist which correctly surfaces `"requires_python": ">=3.5, <4"`, matching https://github.com/sybrenstuvel/python-rsa/blob/version-4.7.1/setup.py#L57 

This has a similar effect as reported in #152 , where if you run `pip2 install rsa`, the package can't be installed and errors with:
```
Collecting rsa
  Downloading rsa-4.7.1.tar.gz (38 kB)
ERROR: Package 'rsa' requires a different Python: 2.7.17 not in '>=3.5, <4'
```

For PY2 projects, the workaround is simply to pin to 4.5. This doesn't seem like a huge deal given that PY2 has reached EOL, but it seems like a regression in the release process nonetheless.

**Comment by sybrenstuvel** [comment]
I've been wanting to streamline the release process & document it properly. Thanks for giving the final push in that direction.

**Comment by sybrenstuvel** [comment]
Streamlined the process by switching to Poetry (8bc1ec89fb629a86c) and documented the release process (913829a342ecc).
