### ISSUE TITLE
Is there a way to reconstruct a public key from jwks with a PublicKey object?

### ISSUE THREAD

**Issue by gcavalcante8808** [sybrenstuvel/python-rsa#190]
Hi Folks,

I'm writing a oldc authentication code to use with lambda@edge and I'd like to use this library as there is a 1MB limit in terms of size (zipped, including libraries and source code).

For that purpose, I just generated a RSA256 json web keys with the respective certificates on `https://mkjwk.org`... 

The generated public key:

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk9xf/cs8bKChrtI9IavV
qxwTtm0ImxJ3yJF+/8tbnLrjMs34Tz/IdqnafcZWfj2j9EEd3tNgyY+9zOUJD3lX
z9bzTfLSrEpTjBfu9/nMuLWGLUzl91hkcuK3elsvwEt63aA8WRUPiRAAubj6nxUF
mQa9gaArYBBeCfvdAVSHk02YhWSu+T+t3LvYWqs1rhIAhWjQMeUEkagDZEL63GNm
dIaz4Mm8ENWSJ0d5c7CZQypm5INTnGYNxO1rL8S250uyWBlBokQqWtX4+DttkmGy
crQEjzLZVS1NjhG+pSWIStjkzs4XJ4gFN0n+G2Avw4XbK8FSlKjYrbJW7JXXB96/
9wIDAQAB
-----END PUBLIC KEY-----
```

```
exponent = 65537
modulus = 18665701776133239352804595345760706958452780914523050832990848957090078835388198831827769314673502199907983956133710746670529960502890976979364137160937128742743531473520867434810240776041644447150561900287387912634724328556464201639235289381872719719530468278453161266510306356827577780813565166652143811324231503707960225415067988746520128800213723156766160377085214363767387996449764033443183111593936419585557529719792415983849980199615430369774301371705966911145024866309238666074303774030485657347087743934618933080295581671150267660967868805951096036505060652396831823099337072924665628744247763617890332229623
```

But when I Try to get the public key, the result is slightly different from my public key, as the public key have a `MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A` value (Key ID maybe?) in the start but the generated doesn't:

```
(Pdb++) print(PublicKey(modulus, exponent).save_pkcs1().decode())
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAk9xf/cs8bKChrtI9IavVqxwTtm0ImxJ3yJF+/8tbnLrjMs34Tz/I
dqnafcZWfj2j9EEd3tNgyY+9zOUJD3lXz9bzTfLSrEpTjBfu9/nMuLWGLUzl91hk
cuK3elsvwEt63aA8WRUPiRAAubj6nxUFmQa9gaArYBBeCfvdAVSHk02YhWSu+T+t
3LvYWqs1rhIAhWjQMeUEkagDZEL63GNmdIaz4Mm8ENWSJ0d5c7CZQypm5INTnGYN
xO1rL8S250uyWBlBokQqWtX4+DttkmGycrQEjzLZVS1NjhG+pSWIStjkzs4XJ4gF
N0n+G2Avw4XbK8FSlKjYrbJW7JXXB96/9wIDAQAB
-----END RSA PUBLIC KEY-----
```

So ... Is there a way to reconstruct a public key from jwks with a PublicKey object?

**Comment by sybrenstuvel** [comment]
This depends on the chosen algorithm:

![image](https://user-images.githubusercontent.com/1092128/158056976-106b61ef-77a7-4953-a5e7-1102c01574d7.png)

You can find in [the Compatibility section of the documentation](https://stuvel.eu/python-rsa-doc/compatibility.html) which standards this RSA library works with.

I'll close this thread for now, but please reopen it if you need more help.
