### ISSUE TITLE
Public key decryption problem

### ISSUE THREAD

**Issue by git-ruoshui** [sybrenstuvel/python-rsa#193]
public_key = PublicKey.load_pkcs1_openssl_pem(RSA_PUBLIC_KEY.encode())
c_text = transform.bytes2int(ciphertext)
decrypted = core.decrypt_int(c_text, public_key.e, public_key.n)
bytes_text = transform.int2bytes(decrypted)  
print(str(bytes_text, encoding="utf-8", errors='ignore'))

'''
>~&&.E'OlPg,.rԸs$#q%uWst9Q*5)(j®ڐCʦà^vaN^s{3st+#W{,1ڂ<頎c1
_Xv
'''

The return value is always garbled(utf-8,gbk,...).   same public key ,java can do it.  why?

**Comment by sybrenstuvel** [comment]
Java is a language, so I don't know what you mean with "java can do it".

You're trying to use plain RSA decryption, but you explain nothing about how the ciphertext got encrypted. There is not enough information to help.

**Comment by git-ruoshui** [comment]
我尝试使用rsa这个库进行公钥解密，同样的密文和公钥，rsa这个库使用上述方法解出来乱码，但是我用Java解出来的不乱码。备注：密文使用Java利用私钥加密

**Comment by git-ruoshui** [comment]
I tried to use the rsa library for public key decryption, the same ciphertext and public key, rsa this library using the above method can not solve the original text (garbled), but I solved it correctly with Java. Note: ciphertext is encrypted using Java using private key.

**Comment by sybrenstuvel** [comment]
There are many different ways in which to use RSA to encrypt something. See https://stuvel.eu/python-rsa-doc/compatibility.html for more info.

**Comment by sybrenstuvel** [comment]
I'll close this thread. If you want to discuss further, please feel free to reopen it.
