### ISSUE TITLE
AttributeError: 'str' object has no attribute 'n'

### ISSUE THREAD

**Issue by Satohsi0Amadeus0XDS0Stars** [sybrenstuvel/python-rsa#195]
I've been tried to decrypt a string using rsa asymmetric encryption in **Python,** when the two keys are created (public key and private key) I store them into a file, so when the string is encrypted I pass to other function in order to decrypt it.

Once the function to decrypt the string is executed requires a **private key** as an input to the function, so when the private key as in input is given it use to decrypt the file using  public key too, but when the decrypt function is executed we got an error:

```
    blocksize = common.byte_size(priv_key.n)
AttributeError: 'str' object has no attribute 'n'
```
I know is about the type of the data, I tried as well to transform into bytes and decode, but it doesn't work, how can I use private key as in input to decrypt a string?

**Comment by sybrenstuvel** [comment]
The function requires a `PrivateKey` object, not a string.

**Comment by jregex** [comment]
so how to convert in object?
