### ISSUE TITLE
No PEM start marker "b'-----BEGIN PUBLIC KEY-----'" found

### ISSUE THREAD

**Issue by keysona** [sybrenstuvel/python-rsa#49]
> system : ubuntu 14.04
> python-version : python 3.4.3
> python-libray : requests , rsa

I use requests library to get **pem** file from internet.
Requests library auto change response string to unicode.
So when I get a  pem file from internet , and pass it to **rsa.PublicKey.load_pkcs1_openssl_pem()**
It raise a exception:
```
Traceback (most recent call last):
  File "login.py", line 43, in <module>
    key = rsa.PublicKey.load_pkcs1_openssl_pem(public_key)
  File "/usr/local/lib/python3.4/dist-packages/rsa/key.py", line 218, in load_pkcs1_openssl_pem
    der = rsa.pem.load_pem(keyfile, 'PUBLIC KEY')
  File "/usr/local/lib/python3.4/dist-packages/rsa/pem.py", line 88, in load_pem
    raise ValueError('No PEM start marker "%s" found' % pem_start)
ValueError: No PEM start marker "b'-----BEGIN PUBLIC KEY-----'" found
```

I view the code, find that which cause that problem is charset.

```
# rsa/pem.py 
# in load_pem function
# for loop
for line in contents.splitlines():
     line = line.strip()
     # Skip empty lines
     if not line:
         continue
     # Handle start marker
     if line == pem_start:
         if in_pem_part:
             raise ValueError('Seen start marker "%s" twice' % pem_start)

         in_pem_part = True
         continue
```
Because **pem_start** is binary string, and my pem file is unicode string.
They never equal.So the exception that I met raise.

I think before compare, maybe be check the **contents** argument?
If it is a unicode string , call b(), then compare?

Sorry, I  am not good at english.

**Comment by sybrenstuvel** [comment]
Can you give me some example code that shows this error?

**Comment by keysona** [comment]
Ok,code is bellow.
```
import requests as req
import json
import rsa
import base64

pub_key_url = 'https://passport.baidu.com/v2/getpublickey'

response = req.get(pub_key_url)

temp = json.loads(response.text.replace("'",'"'))
pub_key = temp.get('pubkey')

print('public_key : ',pub_key)

key = rsa.PublicKey.load_pkcs1_openssl_pem(pub_key)
```

**Comment by sybrenstuvel** [comment]
Try passing `pub_key.encode('ascii')` instead of just `pub_key`, that provides a workaround for this issue. I'll leave this ticket open for now, as at some point it might be nice when the RSA library does this by itself.

**Comment by keysona** [comment]
Thanks.

**Comment by keysona** [comment]
Thanks!!
