### ISSUE TITLE
Random-based tests affect coverage stats

### ISSUE THREAD

**Issue by adamantike** [sybrenstuvel/python-rsa#54]
Even non-code changes affect _coveralls_ results. Random-based execution paths should be detected and unit-tested.

Example: #51

**Comment by sybrenstuvel** [comment]
Good point. As we're not using a pseudo-RNG, we can't simply set a seed to solve this. I also don't feel comfortable testing with a pseudo-RNG while production use uses a real RNG.

I've partially addressed this by ensuring multiple code paths are covered in 46b72a462dbd7955f7e8f13cef1b1a3cb0af2c51 and fec61ece4c1593e79bc52c84cf69a715cd6a9dcd, with more to come.

**Comment by sybrenstuvel** [comment]
9a9e08ce6559f888c345935bac7f85f747fc5f06 seems to remove the code coverage randomness, at least with a few tests I ran here.
