### ISSUE TITLE
The is_prime() function if number < 10 returns a Syntax Error python 2.6

### ISSUE THREAD

**Issue by rendean** [sybrenstuvel/python-rsa#81]
Syntax error occurs in python 2.6 (Scientific Linux release 6.7)  works in python 2.7 

def is_prime(number):

changed it from

return number in {2, 3, 5, 7}

to
..
    # Check for small numbers.
    if number < 10:
        return number in [2, 3, 5, 7]
...

**Comment by sybrenstuvel** [comment]
Marked as invalid, as the report doesn't even include the Python version, or a way to reproduce this issue. My guess is that you're trying to run on Python 2.6, which has been obsolete for years: https://www.python.org/dev/peps/pep-0361/

**Comment by sybrenstuvel** [comment]
Closing as invalid. Scientific Linux is using a Python version that has been marked as obsolete almost three years ago.
