### ISSUE TITLE
Misunderstanding description of rsa.PrivateKey.save_pkcs1

### ISSUE THREAD

**Issue by pravic** [sybrenstuvel/python-rsa#86]
https://stuvel.eu/python-rsa-doc/reference.html#rsa.PrivateKey.save_pkcs1:

> Saves the public key in PKCS#1 DER or PEM format.

But in fact it saves a private key.

**Comment by sybrenstuvel** [comment]
This was already fixed in f0627bed3e8815e8138fbe72b740483f69d6ac7a, but I never updated the online documentation as the fix hasn't been released yet as a stable Python-RSA version.
