### ISSUE TITLE
Probabilistic Signature Scheme for RSA key signing

### ISSUE THREAD

**Issue by zhaoxx063** [sybrenstuvel/python-rsa#91]
question 1:  Does the current version of python-rsa (v3.4) having support probabilistic signature scheme?

question 2: Do you have a plan to support it ?

**Comment by sybrenstuvel** [comment]
1. I don't know what it is, so probably not. 
2. Because I don't need it myself I won't implement it myself. If you can write an implementation, I'm always open to pull requests.

**Comment by zhaoxx063** [comment]
You can read some things about it  in  section 8.1 of this article (https://tools.ietf.org/html/rfc3447), and also another (https://rsapss.hboeck.de/rsapss.pdf). 

The C/C++ implementation can be find the following URL:
"https://www.cryptopp.com/wiki/Rsa_signature_schemes#RSA_Probabilistic_Signature_Scheme_with_Recovery"

RSA Probabilistic Signature Scheme with Recovery
////////////////////////////////////////////////
// Generate keys
AutoSeededRandomPool rng;

InvertibleRSAFunction params;
params.GenerateRandomWithKeySize(rng, 1536);

RSA::PrivateKey privateKey(params);
RSA::PublicKey publicKey(params);

// Signing      
RSASS<PSSR, SHA1>::Signer signer(privateKey);
RSASS<PSSR, SHA1>::Verifier verifier(publicKey);

// Setup
byte message[] = "RSA-PSSR Test";
size_t messageLen = sizeof(message);      

////////////////////////////////////////////////
// Sign and Encode
SecByteBlock signature(signer.MaxSignatureLength(messageLen));

size_t signatureLen = signer.SignMessageWithRecovery(rng, message,
    messageLen, NULL, 0, signature);

// Resize now we know the true size of the signature
signature.resize(signatureLen);

////////////////////////////////////////////////
// Verify and Recover
SecByteBlock recovered(
    verifier.MaxRecoverableLengthFromSignatureLength(signatureLen)
);

DecodingResult result = verifier.RecoverMessage(recovered, NULL,
    0, signature, signatureLen);

if (!result.isValidCoding) {
    throw Exception(Exception::OTHER_ERROR, "Invalid Signature");
}

////////////////////////////////////////////////
// Use recovered message
//  MaxSignatureLength is likely larger than messageLength
recovered.resize(result.messageLength);
...

**Comment by sybrenstuvel** [comment]
Send a pull request for a pure-Python implementation, and I'll consider it for inclusion in this library. Otherwise I don't have the time to implement this for you.
