### ISSUE TITLE
rsa.encrypt() function, can not encrypt a text with private key  

### ISSUE THREAD

**Issue by zhaoxx063** [sybrenstuvel/python-rsa#92]
When I use rsa.encrypt() to encrypt a text with my private key, it came across a wrong prompt like following:
-------------------------
'PublicKey' object has no attribute 'blinded_decrypt'
 ------------------------
If the encrypt() function only support public key to encrypt a text,  it is very unreasonable!
Do you have a plan to enhance it？

**Comment by sybrenstuvel** [comment]
Why is that unreasonable? Encryption with a private key is called signing. Of course this is supported. See section [5.4. Signing and verification](https://stuvel.eu/python-rsa-doc/usage.html#signing-and-verification) for more info.

**Comment by ArsHinMQ** [comment]
Correct me if I'm wrong, but shouldn't be a method for unsigning the signed message with the public key?
For example, I've signed a message with my private key, and I want everyone with the public key reads the message and KNOW that I've signed it.
How would they do that?
